stages:
 - build

hqvc_frontend:
  stage: build
  image: stieneee/docker-in-ubuntu:latest
  services:
    - docker:dind
  before_script: 
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - curl -fsSL https://deb.nodesource.com/setup_20.x | bash - &&\ apt-get install -y nodejs
    - apt-get update
    - curl https://install.meteor.com/ | sh
    - npx browserslist@latest --update-db
    - mkdir -p /tmp/meteor-build/
    - ver=`cat /builds/hqvc/meteor-advancesearch/package.json | grep version | grep -oE "\"[^\"]+\"," | sed "s/[\",]//g"`
  script:
    - npm i
    - meteor build --allow-superuser --architecture os.linux.x86_64 --server https://holyquran.site --directory /tmp/meteor-build/
    - cp /builds/hqvc/meteor-advancesearch/Docker* /tmp/meteor-build/bundle/
    - cd /tmp/meteor-build/bundle/
    - docker build -t "hqvc:$ver" .