variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375/
  IMAGE_NAME: hqvc
  IMAGE_TAG: 6.16.1b

stages:
  - build
  - deploy


hqvc_frontend:
  stage: build
  image: docker:stable
  before_script: 
    - sudo npm install -g npm
    - meteor update
    - npm update
    - meteor update --all-packages
    - npx browserslist@latest --update-db
    - meteor npm install
    - ver=`cat package.json | grep version | grep -oE "\"[^\"]+\"," | sed "s/[\",]//g"`
  script:
    - pwd
    - meteor build --architecture os.linux.x86_64 --server https://holyquran.site
    - mkdir ../temp
    - tar -xzf ../*.tar.gz -C ../temp
    - cp Docker* ../temp

aws_deploy:
   stage: deploy
   image: docker:stable
   services:
    - docker:dind
   variables:
     DOCKER_TLS_CERTDIR: "" 
   script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - docker build  ../temp -t "hqvc:$ver"
    - rm -fr ../temp
 