variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375/
  IMAGE_NAME: hqvc
  IMAGE_TAG: 6.16.1b

stages:
  - build
  - deploy


hqvc_frontend:
  stage: build
  image: blurri/meteor-node
  variables:
      METEOR_ALLOW_SUPERUSER: "true"
  before_script: 
    - meteor update
    - meteor update --all-packages
    - meteor npm install
    - ver=`cat package.json | grep version | grep -oE "\"[^\"]+\"," | sed "s/[\",]//g"`
  script:
    - meteor build /builds/hqvc/meteor-advancesearch --architecture os.linux.x86_64 --server https://holyquran.site
    - mkdir /builds/hqvc/meteor-advancesearch/temp
    - tar -xzf /builds/hqvc/meteor-advancesearch/*.tar.gz -C /builds/hqvc/meteor-advancesearch/temp
    - cp Docker* /builds/hqvc/meteor-advancesearch/temp

aws_deploy:
   stage: deploy
   image: docker:stable
   services:
     - docker:dind
   variables:
     DOCKER_TLS_CERTDIR: "/certs"
   script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - docker build  /builds/hqvc/meteor-advancesearch/temp -t "hqvc:$ver"
    - rm -fr /builds/hqvc/meteor-advancesearch/temp
 